# Generated by Django 3.2.8 on 2021-10-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreastCancerChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('surname', models.CharField(max_length=255, null=True)),
                ('mean_radius', models.FloatField(default=17.99, null=True)),
                ('mean_texture', models.FloatField(default=10.99, null=True)),
                ('mean_perimeter', models.FloatField(default=122.8, null=True)),
                ('mean_area', models.FloatField(default=1001.0, null=True)),
                ('mean_smoothness', models.FloatField(default=0.1184, null=True)),
            ],
        ),
    ]
